sections:
  - contacts
  - positions
  - educations
  - projects
keywords:
  - llm
  - rl
  - agent[s]?
  - rag
  - retrieval
  - \d+[\%x]?
  - ml
  - ai
  - eda
  - multimodal
  - python
  - C\+\+
  - optimization
  - genai
  - nlp
  - mle
  - async
