sections:
  - contacts
  - positions
  - educations
  - projects
injection:
  - fair: true
    to: index.html
  - fair: false
    to: alt.html
keywords:
  - llm
  - rl
  - agent[s]?
  - rag
  - retrieval
  - \d+[\%]?
  - ml
  - ai
  - eda
  - multimodal
  - python
  - C++
