sections:
  - contacts
  - positions
  - projects
  - educations
keywords:
  - llm
  - rl
  - agent[s]?
  - rag
  - retrieval
  - \d+[\%x]?
  - ml
  - ai
  - eda
  - multimodal
  - python
  - C\+\+
  - optimization
  - genai
  - nlp
  - mle
  - async
  - cuda
  - sql
  - gpu
  - pytorch
  - pandas
